PUBLIC_CONFIG = {'site': {'title': 'FastoTV', 'keywords': 'video,cloud,iptv,player',
                          'small_description': 'FastoTV - cross-platform solution for watching tv.',
                          'domain': 'fastotv.com'},
                 'company': {'title': 'FastoGT', 'domain': 'https://fastogt.com'},
                 'support': {'contact_email': 'support@fastogt.com',
                             'contact_address': 'Republic of Belarus, Minsk',
                             'community_channel': 'https://discord.gg/cnUXsws',
                             'partners': [{'company': 'Tathya Technologies Pvt Ltd (OPC)',
                                           'website': 'https://tathyatechnologies.com',
                                           'country': 'India, Bangladesh'}],
                             'brands': [{'name': 'DreamBoxs', 'website': 'http://dreamboxs.co.uk',
                                         'country': 'United Kingdom'}]},
                 'project': {'version': '1.0.0', 'version_type': 'release',
                             'github': {'issues': 'https://github.com/fastogt/fastotv_site_new/issues',
                                        'repo': 'https://github.com/fastogt/fastotv_site_new'}
                             },
                 'player': {'name': 'FastoTV', 'name_lowercase': 'fastotv', 'version': '1.17.0',
                            'version_type': 'release',
                            'android_playstore_link': 'https://play.google.com/store/apps/details?id=com.fastotv'}
                 }
